kiudee/cs-ranking

csrank/tests/test_choice_functions.py
csrank/tests/test_discrete_choice.py
csrank/tests/test_fate.py
csrank/tests/test_ranking.py
requirements.txt

Since apparently `tf.keras` uses `learning_rate` too now, we should also switch over to that name. With this change we're also compatible with the latest `keras` again.
While making this change I also noticed and fixed a small typo.
Ran all tests.
Previous discussion: https://github.com/kiudee/cs-ranking/pull/56

Keras update

---

pytest.ini

We do not have control about any of these warnings except the last one.
And that one is harmless in a testing context.
Maintaining a list of these filters is cumbersome. I wish there was some
way to automatically ignore all warnings caused by third party code, but
unfortunately I don't think there currently is. I've opened
https://github.com/pytest-dev/pytest/issues/6191
to discuss this.
I still think it is worthwhile to filter these warnings, because
otherwise they drown out those warnings that are actually relevant.
Ran all tests.
Related to https://github.com/kiudee/cs-ranking/issues/59.

Ignore some warnings

---

pytest.ini

Out of our control.
Fixes #74
The goal is to have the testsuite not emit any warnings. That way we can easily catch new warnings as they arise.
Ran all tests.

Ignore numpy warning that is caused by theano

---

.coveragerc
.travis.yml
csrank/choicefunction/generalized_linear_model.py
csrank/dataset_reader/labelranking/survey_dataset_reader.py
csrank/discretechoice/generalized_nested_logit.py
csrank/discretechoice/mixed_logit_model.py
csrank/discretechoice/multinomial_logit_model.py
csrank/discretechoice/nested_logit_model.py
csrank/discretechoice/paired_combinatorial_logit.py
requirements.txt
scripts/create_testenv.sh

This is a clone of #80.
Imputer was removed from preprocessing in
https://github.com/scikit-learn/scikit-learn/pull/13796. To be
compatible with newer scikit-learn versions, we need to stop using it.
impute.SimpleImputer seems to be a viable replacement.
This caused failures on travis.
The latest sklearn caused failures on travis.
Ran all tests with sklearn 0.22.
Impacts https://github.com/kiudee/cs-ranking/pull/65, where the CI fails because of this.

Replace imputer usage

---

.travis.yml

The [travis-sphinx](https://github.com/Syntaf/travis-sphinx) script has not been maintained for a while and sometimes causes failing builds.
Since travis-ci has a native method for deploying to GitHub pages, it is preferable to use it. 
Has not been tested.
--

Replace travis-sphinx deploy script with travis-ci’s native deploy method

---

.travis.yml

Adds a webhook to the .travis.yml file.
The tests are executed in parallel and the last test to finish updates the coverage report. This change should fix this behaviour and produce actually accurate coverage reports.
By doing this pull request.
--

Let travis-ci notify coveralls to merge coverage reports

---

.pre-commit-config.yaml
.travis.yml
requirements-dev.txt

Run `black` pre-commit and on CI.
As a follow up to https://github.com/kiudee/cs-ranking/pull/78, we should run `black` locally pre-commit and verify that this was done on CI. Otherwise the formatting would slowly shift away from the black standard again.
By creating this PR.
#78

Add pre-commit configuration and use it in CI

---

CONTRIBUTING.rst

Finishing up #78 and #100 with some documentation.
New contributors should apply the pre-commit hooks and understand what they are doing.
--
#78, #100

Document pre-commit hooks

---

.codecov.yml
.travis.yml
README.rst
docs/intro.rst

Remove coveralls from the repository and set up codecov instead.
We currently use Coveralls to report coverage statistics for each new pull request. Sadly, it does not handle parallel builds correctly and thus is quite useless.
Codecov seems to be widely used, better maintained and can be configured in detail.
By creating this pull request

Replace coveralls with codecov

---

.pre-commit-config.yaml
CONTRIBUTING.rst
README.rst
docs/api.rst
docs/api/choicefunction.rst
docs/api/objectranking.rst
docs/intro.rst

This fixes all the style issues and mistakes reported by `doc8` and registers `doc8` as a pre-commit hook (which will also be enforced by travis) to make sure the docs stay "clean".
There were two mistakes, one of which @kiudee [noticed](https://github.com/kiudee/cs-ranking/pull/106#discussion_r398800124) previously. The other one was an anonymous link I forgot to specify in `CONTRIBUTING.rst`.
Catching those errors is undeniably valuable. The style-checking is opinionated and could be argued, but I think having a uniform style is very valuable as well.
Ran `doc8`, this PR.
Closes #103.

Check docs for errors and style mistakes with doc8

---

.flake8
csrank/__init__.py
csrank/choicefunction/__init__.py
csrank/core/__init__.py
csrank/core/feta_network.py
csrank/dataset_reader/__init__.py
csrank/dataset_reader/choicefunctions/__init__.py
csrank/dataset_reader/discretechoice/__init__.py
csrank/dataset_reader/discretechoice/discrete_choice_data_generator.py
csrank/dataset_reader/dyadranking/__init__.py
csrank/dataset_reader/labelranking/__init__.py
csrank/dataset_reader/objectranking/__init__.py
csrank/dataset_reader/objectranking/object_ranking_data_generator.py
csrank/discretechoice/__init__.py
csrank/objectranking/__init__.py
csrank/tests/test_metrics.py
requirements-dev.txt
setup.py

Fix and enable flake8 error "imported but unused"

---

csrank/choicefunction/generalized_linear_model.py
csrank/core/cmpnet_core.py
csrank/core/fate_linear.py
csrank/core/fate_network.py
csrank/core/feta_linear.py
csrank/core/feta_network.py
csrank/core/pairwise_svm.py
csrank/core/ranknet_core.py
csrank/discretechoice/baseline.py
csrank/discretechoice/generalized_nested_logit.py
csrank/discretechoice/nested_logit_model.py
csrank/discretechoice/paired_combinatorial_logit.py
csrank/objectranking/baseline.py
csrank/objectranking/cmp_net.py
csrank/objectranking/expected_rank_regression.py
csrank/objectranking/list_net.py
csrank/tuning.py

Part of #94 and #116.
The scikit-learn estimator API requires us to store all `__init__` parameters *unmodified*. Validation should be delayed as late as possible. That is because `set_params` could override those parameters. See https://scikit-learn.org/stable/developers/develop.html#random-numbers.
I'm using the pattern of setting `self.random_state_` at the beginning of every fit function. In theory that is not always needed, since often the random state is only used in one function. I think its less error-prone to always do it the same way though.
Ran the pre-commit hooks and the test-suite.
#94 and #116

Delay random state validation

---

requirements-dev.txt

Pulled out of #118, since it unbreaks travis and is also impacting other PRs (#119).
Forgotten in b031340483bf21f4bf7cbba0c3b1b68fe92c7c7a. Hopefully fixes
the tests on travis, which currently fail because pygmo isn't getting
installed. The travis test script installs dependencies from
requirements-dev.txt.
Checks on travis are broken due to a missing dependency.
Fixed travis on #118.

Add pygmo to requirements-dev

---

csrank/choicefunction/fate_choice.py
csrank/core/fate_network.py
csrank/tests/test_choice_functions.py

Previously we were passing on **kwargs, but also specifying some
arguments explicitly which meant they were not included in **kwargs and
not passed on.
To make this more maintainable, we now also delegate the documentation
to the core.
#126 
Fixes #126

Properly pass on fit kwargs to the core network

---

csrank/choicefunction/generalized_linear_model.py
csrank/discretechoice/generalized_nested_logit.py
csrank/discretechoice/mixed_logit_model.py
csrank/discretechoice/multinomial_logit_model.py
csrank/discretechoice/nested_logit_model.py
csrank/discretechoice/paired_combinatorial_logit.py

Continuation of ab058621e836ec230d27b516f9f53fbfc063d28f. In that commit
I only searched for the `not in` pattern, but the cases fixed here
actually check the reverse.
#128 
Testsuite & pre-commit hooks.
Fixes #128. Technically a breaking change, but only exposes pre-existing bugs.

Raise ValueError on some more unknown variants

---

csrank/choicefunction/baseline.py

I believe this fixes #127, though I'm not entirely sure what the intended behaviour of the baseline choice function is. Why does it expect `Y` on `predict`? Even if it is a baseline and simply predicts the mean, shouldn't it take `Y` on fit instead?
#127
Testsuite, pre-commit hooks.
Fixes #127.

Fix baseline choice parameter

---

HISTORY.rst
csrank/choicefunction/cmpnet_choice.py
csrank/choicefunction/fate_choice.py
csrank/choicefunction/feta_choice.py
csrank/choicefunction/ranknet_choice.py
csrank/core/cmpnet_core.py
csrank/core/fate_network.py
csrank/core/feta_network.py
csrank/core/ranknet_core.py
csrank/discretechoice/cmpnet_discrete_choice.py
csrank/discretechoice/fate_discrete_choice.py
csrank/discretechoice/feta_discrete_choice.py
csrank/discretechoice/ranknet_discrete_choice.py
csrank/objectranking/cmp_net.py
csrank/objectranking/fate_object_ranker.py
csrank/objectranking/feta_object_ranker.py
csrank/objectranking/list_net.py
csrank/objectranking/rank_net.py

As discussed in https://github.com/kiudee/cs-ranking/pull/119. The
reasoning is that we don't have good reason to override those, the
library user will likely have to tune them anyways (or use a different
optimizer altogether). At the same time, they make the design proposed
in #119 (passing uninitialized optimizers and their parameters
separately) more difficult.
https://github.com/kiudee/cs-ranking/pull/119#issuecomment-639525631
Tests & pre-commit hooks.
Part of #119 and thus part of #116.

Do not override the optimizer's default parameters

---

HISTORY.rst
csrank/choicefunction/cmpnet_choice.py
csrank/choicefunction/fate_choice.py
csrank/choicefunction/feta_choice.py
csrank/choicefunction/ranknet_choice.py
csrank/core/cmpnet_core.py
csrank/core/fate_network.py
csrank/core/feta_network.py
csrank/core/ranknet_core.py
csrank/discretechoice/cmpnet_discrete_choice.py
csrank/discretechoice/fate_discrete_choice.py
csrank/discretechoice/feta_discrete_choice.py
csrank/discretechoice/ranknet_discrete_choice.py
csrank/learner.py
csrank/objectranking/cmp_net.py
csrank/objectranking/fate_object_ranker.py
csrank/objectranking/feta_object_ranker.py
csrank/objectranking/list_net.py
csrank/objectranking/rank_net.py
csrank/tests/test_choice_functions.py
csrank/tests/test_discrete_choice.py
csrank/tests/test_fate.py
csrank/tests/test_ranking.py
docs/notebooks/FATE-Net-DC.ipynb
docs/notebooks/FATE-Net-Ranking.ipynb
docs/notebooks/Rank-Net-Choice.ipynb
requirements-dev.txt
setup.py

An initialized optimizer is a tensorflow object, which (at least in
graph mode in tf1) is not deepcopy-able. Even if we were able to
deeocopy it, we probably wouldn't want to since it contains state.
Scikit-learn needs to be able to deepcopy an estimators arguments so
that it can create copies and derivatives of it.
Instead we require the uninitialized optimizer and its parameters to be
passed to our learners separately. The learner can then initialize the
optimizer as needed.
~I have only done this for `CmpNet` so far. We'd have to do it for all estimators that take an optimizer (i.e. pretty much all of them). Before I do that, I would like some feedback on the general approach. I went with a function with out arguments since that retains the most flexibility. It may be a bit weird to …

Require uninitialized optimizers for our learners

---

csrank/choicefunction/cmpnet_choice.py
csrank/choicefunction/fate_choice.py
csrank/choicefunction/feta_choice.py
csrank/choicefunction/ranknet_choice.py
csrank/core/cmpnet_core.py
csrank/core/fate_network.py
csrank/core/feta_linear.py
csrank/core/feta_network.py
csrank/core/ranknet_core.py
csrank/discretechoice/cmpnet_discrete_choice.py
csrank/discretechoice/fate_discrete_choice.py
csrank/discretechoice/feta_discrete_choice.py
csrank/discretechoice/generalized_nested_logit.py
csrank/discretechoice/mixed_logit_model.py
csrank/discretechoice/multinomial_logit_model.py
csrank/discretechoice/nested_logit_model.py
csrank/discretechoice/paired_combinatorial_logit.py
csrank/discretechoice/ranknet_discrete_choice.py
csrank/learner.py
csrank/objectranking/cmp_net.py
csrank/objectranking/fate_object_ranker.py
csrank/objectranking/feta_object_ranker.py
csrank/objectranking/list_net.py
csrank/objectranking/rank_net.py

Pulling out the changes of https://github.com/kiudee/cs-ranking/pull/116 that are ready for merge now. As I said in https://github.com/kiudee/cs-ranking/pull/116#issuecomment-650589268, this brings us very close to passing the "default-constructible" test. I think/hope that will be the highest hurdle for sklearn api compatibility.
Outstanding issues are the kernel-regularizers and https://github.com/scikit-learn/scikit-learn/issues/17756.
See #116.
Linters & tests.
Impacts #116, but doesn't close it.

Misc fixes for default-constructibility of our learners

---

csrank/choicefunction/cmpnet_choice.py
csrank/choicefunction/ranknet_choice.py
csrank/core/cmpnet_core.py
csrank/core/pairwise_svm.py
csrank/core/ranknet_core.py
csrank/discretechoice/cmpnet_discrete_choice.py
csrank/discretechoice/ranknet_discrete_choice.py
csrank/objectranking/cmp_net.py
csrank/objectranking/list_net.py
csrank/objectranking/rank_net.py

The next part in the #116 saga: I'm starting to remove instance attributes that are not parameters. The first one is `instance_thresholds`, which doesn't look like a useful feature to me. There is two distinct use cases, one simply reduces the dataset size and the other picks a simpler model. I have removed the first and replaced the second by an explicit parameter.
Less surprising behavior and #116. 
Test suite and lints.

Remove threshold instances

---

.travis.yml
csrank/choicefunction/baseline.py
csrank/choicefunction/generalized_linear_model.py
csrank/core/cmpnet_core.py
csrank/core/fate_network.py
csrank/core/feta_network.py
csrank/core/pairwise_svm.py
csrank/core/ranknet_core.py
csrank/discretechoice/baseline.py
csrank/discretechoice/generalized_nested_logit.py
csrank/discretechoice/mixed_logit_model.py
csrank/discretechoice/multinomial_logit_model.py
csrank/discretechoice/nested_logit_model.py
csrank/discretechoice/paired_combinatorial_logit.py
csrank/dyadranking/fate_dyad_ranker.py
csrank/objectranking/baseline.py
csrank/objectranking/expected_rank_regression.py
csrank/objectranking/list_net.py

The model inherently is an "attribute that [has] been estimated from the
data"[1], i.e. it should be initialized in fit and have a trailing
underscore.
[1] https://scikit-learn.org/stable/developers/develop.html#rolling-your-own-estimator
Working on only saving the model parameters in init to make sure our estimators are stateless and match the scikit-learn estimator spec.
Tests + pre-commit.
Related #94, #116.

Do not initialize the model in init

---

csrank/choicefunction/cmpnet_choice.py
csrank/choicefunction/fate_choice.py
csrank/choicefunction/feta_choice.py
csrank/constants.py
csrank/core/cmpnet_core.py
csrank/core/fate_network.py
csrank/core/feta_network.py
csrank/core/ranknet_core.py
csrank/discretechoice/cmpnet_discrete_choice.py
csrank/discretechoice/fate_discrete_choice.py
csrank/discretechoice/feta_discrete_choice.py
csrank/learner.py
csrank/objectranking/cmp_net.py
csrank/objectranking/list_net.py
csrank/tests/test_fate.py

Changes are on top of #154 to avoid merge conflicts.
~**#154 should be reviewed first.**~
The mechanism is replaced by the already established prefixing and an
explicit prefix whitelist. This is more explicit than just passing
around "raw" kwargs, easier to understand and satisfies the "no
attributes in init" check for scikit-learn estimators.
Pre-commit and test suite.
Related to #94, #116, #146.

Do not store kwargs

---

csrank/choicefunction/choice_functions.py
csrank/choicefunction/cmpnet_choice.py
csrank/choicefunction/fate_choice.py
csrank/choicefunction/fatelinear_choice.py
csrank/choicefunction/feta_choice.py
csrank/choicefunction/fetalinear_choice.py
csrank/choicefunction/generalized_linear_model.py
csrank/choicefunction/pairwise_choice.py
csrank/choicefunction/ranknet_choice.py
csrank/core/fate_linear.py
csrank/core/fate_network.py
csrank/core/feta_linear.py
csrank/core/feta_network.py
csrank/core/pairwise_svm.py
csrank/core/ranknet_core.py
csrank/discretechoice/generalized_nested_logit.py
csrank/discretechoice/likelihoods.py
csrank/discretechoice/mixed_logit_model.py
csrank/discretechoice/multinomial_logit_model.py
csrank/discretechoice/nested_logit_model.py
csrank/discretechoice/paired_combinatorial_logit.py
csrank/objectranking/expected_rank_regression.py
csrank/objectranking/list_net.py

After removing some big sets (#154, #155), this PR is supposed to take care of the ["long tail"](https://github.com/kiudee/cs-ranking/pull/116#issuecomment-682708859) of failures of the `check_no_attributes_set_in_init` sklearn estimator check.
~This is a work in progress. Builds on #154, #155 which should be reviewed first.~
Also see the commit message:
Most of these attributes are actually initialized during fit and the
values do not need to be set in init. To conform the the scikit-learn
estimator API, we should not set them in init and postfix values that
are learned from the data with an underscore.
This takes care of most of the remaining attributes in init. The
remaining attributes are due to `construct_model` being called in
`__init__`, which cannot currently be easily fixed. A …

Take care of the long tail of attributes in init

---

csrank/choicefunction/baseline.py
csrank/choicefunction/cmpnet_choice.py
csrank/choicefunction/fate_choice.py
csrank/choicefunction/fatelinear_choice.py
csrank/choicefunction/feta_choice.py
csrank/choicefunction/fetalinear_choice.py
csrank/choicefunction/generalized_linear_model.py
csrank/choicefunction/pairwise_choice.py
csrank/choicefunction/ranknet_choice.py
csrank/core/cmpnet_core.py
csrank/core/fate_linear.py
csrank/core/fate_network.py
csrank/core/feta_linear.py
csrank/core/feta_network.py
csrank/core/pairwise_svm.py
csrank/core/ranknet_core.py
csrank/discretechoice/baseline.py
csrank/discretechoice/generalized_nested_logit.py
csrank/discretechoice/mixed_logit_model.py
csrank/discretechoice/model_selector.py
csrank/discretechoice/multinomial_logit_model.py
csrank/discretechoice/nested_logit_model.py
csrank/discretechoice/paired_combinatorial_logit.py
csrank/discretechoice/pairwise_discrete_choice.py
csrank/dyadranking/fate_dyad_ranker.py
csrank/learner.py
csrank/objectranking/baseline.py
csrank/objectranking/expected_rank_regression.py
csrank/objectranking/list_net.py
csrank/objectranking/rank_svm.py

Creates a `_pre_fit` function to bridge the gap between `__init__` and `fit`: Everything which initializes some state, but does not actually depend on the data, belongs there. This separates concerns a bit and makes it possible to inherit those initializations.
I thought about making this an implicit wrapper (a wrapper defined in `learner` that inherits signature & docs and automatically prepends a call to `pre_fit` to every `fit` call). This might be possible with [`wrapt`](https://wrapt.readthedocs.io/en/latest/) and a [meta-class](https://stackoverflow.com/questions/8100166/inheriting-methods-docstrings-in-python), but it would be a little complex. Since it would also be less explicit, it might be a bit confusing for people who are not very familiar with the code. So I just went with …

Move stateful initialization to a pre_fit function

---

csrank/dataset_reader/dataset_reader.py

There is a default method implementation, so there is no reason to mark
it abstract. The marker makes it impossible to instantiate
ChoiceDatasetGenerator, which does not explicitly override the default
implementation.
Fixes #166
Testsuite & lints.

Remove abstract marker on get_train_test_datasets

---

csrank/dataset_reader/choicefunctions/choice_data_generator.py
csrank/tests/test_pareto_dataset.py

The Pareto problem generation re-used the same centroid for 10 times (which seems to be a bug) and generated invalid elements when `n_instances` was not a multiple of 10. This tries to fix these problems an adds some documentation on the things @kiudee cleared up for me. This is a result of https://github.com/kiudee/cs-ranking/pull/164#discussion_r522267387.
Ran the new test, relying on CI for the rest.

Pareto: Genereate unique centroids, documentation, test

---

.travis.yml
tox.ini

Travis appears to be using 3.7.1, which causes failing builds.
This pull request replaces the python version travis-ci uses (3.7), which appears to default to 3.7.1 instead of the latest version, by 3.7.9.
Currently the builds are failing, due to a bug present in 3.7.1 (example: https://github.com/kiudee/cs-ranking/pull/178/checks?check_run_id=2149548100).

[WIP] Force travis-ci to use 3.7.9

---

csrank/choicefunction/__init__.py
csrank/choicefunction/feta_choice.py
csrank/discretechoice/__init__.py
csrank/discretechoice/feta_discrete_choice.py
csrank/modules/collection.py
csrank/modules/instance_reduction.py
csrank/modules/scoring/__init__.py
csrank/modules/scoring/feta.py
csrank/objectranking/__init__.py
csrank/objectranking/feta_object_ranker.py
csrank/tests/test_choice_functions.py
csrank/tests/test_discrete_choice.py
csrank/tests/test_ranking.py

This adds pytorch versions of the FETA estimators. ~It builds on (and currently includes the commits of) #164, which should be reviewed first.~ This is now ready for review.
Part of the ongoing pytorch migration.
I have added the FETA estimators to the existing tests for discrete choice, general choice and object ranking. I used the test suite and the linters to check the changes.
Related to #125.
This depends on what you consider as the base. It is a new feature for the pytorch migration branch, but a breaking change on master.

PyTorch migration: Add FETA estimators

---

csrank/choicefunction/__init__.py
csrank/choicefunction/cmpnet_choice.py
csrank/discretechoice/__init__.py
csrank/discretechoice/cmpnet_discrete_choice.py
csrank/modules/object_mapping.py
csrank/modules/scoring/__init__.py
csrank/modules/scoring/cmpnet.py
csrank/objectranking/__init__.py
csrank/objectranking/cmpnet_object_ranker.py
csrank/tests/test_choice_functions.py
csrank/tests/test_discrete_choice.py
csrank/tests/test_ranking.py

This adds pytorch versions of the CmpNet estimators. ~It builds on (and currently includes the commits of) #164 and #183, which should be reviewed first.~ I thought these PRs could be reviewed more independently, but it turns out that CmpNet heavily depends on the components that were introduced for FETA.
This is now ready for review.
Part of the ongoing pytorch migration.
I have added the CmpNet estimators to the existing tests for discrete choice, general choice and object ranking. I have checked the changes with our set of linters and the test suite.
Related to #125.
This depends on what you consider as the base. It is a new feature for the pytorch migration branch, but a breaking change on master.

PyTorch migration: Add CmpNet estimators

---

csrank/choicefunction/feta_choice.py
csrank/discretechoice/feta_discrete_choice.py
csrank/objectranking/feta_object_ranker.py

I missed documentation for the `activation` parameter when adding the FETA based estimators in #183.
See description.
I ran the linters.
No issues, but this is a follow up to #183.
"Bug fix" is the closest match. This does not affect the functionality though.

Add missing activation documentation for FETA

---

HISTORY.rst
README.rst
csrank/choicefunction/__init__.py
csrank/choicefunction/ranknet_choice.py
csrank/discretechoice/__init__.py
csrank/discretechoice/ranknet_discrete_choice.py
csrank/modules/scoring/__init__.py
csrank/modules/scoring/ranknet.py
csrank/objectranking/__init__.py
csrank/objectranking/ranknet_object_ranker.py
csrank/tests/test_choice_functions.py
csrank/tests/test_discrete_choice.py
csrank/tests/test_ranking.py

This adds pytorch versions of the CmpNet estimators.
Part of the ongoing pytorch migration.
I have added the RankNet estimators to the existing tests for discrete choice, general choice and object ranking. I have checked the changes with our set of linters and the test suite.
Related to #125.
This depends on what you consider as the base. It is a new feature for the pytorch migration branch, but a breaking change on master.

PyTorch migration: Add RankNet estimators

---

HISTORY.rst
README.rst
csrank/choicefunction/cmpnet_choice.py
csrank/choicefunction/fate_choice.py
csrank/choicefunction/feta_choice.py
csrank/choicefunction/ranknet_choice.py
csrank/discretechoice/cmpnet_discrete_choice.py
csrank/discretechoice/fate_discrete_choice.py
csrank/discretechoice/feta_discrete_choice.py
csrank/discretechoice/ranknet_discrete_choice.py
csrank/modules/scoring/cmpnet.py
csrank/objectranking/cmpnet_object_ranker.py
csrank/objectranking/fate_object_ranker.py
csrank/objectranking/feta_object_ranker.py
csrank/objectranking/ranknet_object_ranker.py
csrank/tests/test_choice_functions.py
csrank/tests/test_discrete_choice.py
csrank/tests/test_ranking.py
docs/api/choicefunction.rst
docs/api/discretechoice.rst
docs/api/objectranking.rst

This collects some misc fixes, changes and updates regarding the pytorch migration. I have updated the status in the README. The pytorch version does not have feature parity, but it is now at a point where it should be a viable replacement for at least some of the use cases.
Part of the ongoing pytorch migration.
I ran the test suite and used our set of linters.
Related to #125. I think the issue can be closed once the pytorch migration branch has been merged into master.
This contains various documentation changes as well as a breaking change to the CmpNet estimators.

PyTorch migration: Finishing touches

---

HISTORY.rst
csrank/__init__.py
csrank/dataset_reader/discretechoice/discrete_choice_data_generator.py
csrank/dataset_reader/discretechoice/letor_listwise_discrete_choice_dataset_reader.py
csrank/dataset_reader/discretechoice/mnist_discrete_choice_dataset_reader.py
csrank/dataset_reader/discretechoice/sushi_discrete_choice_dataset_reader.py
csrank/dataset_reader/discretechoice/tag_genome_discrete_choice_dataset_reader.py
csrank/dataset_reader/discretechoice/util.py
csrank/dataset_reader/objectranking/util.py
csrank/discretechoice/discrete_choice.py
csrank/objectranking/expected_rank_regression.py
csrank/objectranking/rank_svm.py
csrank/objectranking/util.py
csrank/tests/test_discrete_choice.py
csrank/tests/test_pareto_dataset.py
csrank/util.py
noxfile.py
poetry.lock
pyproject.toml

Remove `dataset_reader` from top level imports and make all data dependencies optional in `pyproject.toml`
The dataset generators are not needed by users who only want to use the learners. Moreover, the [pygmo](https://esa.github.io/pygmo2/) library is notoriously difficult to install on Windows (I was only able to do it using Anaconda and very specific version combinations of packages).
Running all tests. Check if importing the library works without error when only installing base dependencies.
Part of #140.

Make data dependencies optional

---

poetry.lock
pyproject.toml

This pull request removes unnecessary dependencies and widens the dependency ranges where possible.
Smaller dependency ranges make the library difficult to install, especially for dependencies still on 0.x.
All versions were tested locally by pinning each version separately and seeing if all tests pass.

Increase dependency ranges
